name: Build Windows executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and build EXE
        run: |
          python -m pip install --upgrade pip
          pip install reportlab pypdf pyinstaller
          pyinstaller --noconsole --onefile --name "LsMaker" 
barcode_overlay_gui.py
          # Eğer ana dosyan farklıysa (örnek: LsMaker.py), yukarıdaki 
satırda dosya adını değiştir

      - name: List dist folder
        if: always()
        run: dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/LsMaker.exe

