name: Build Windows executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install reportlab pypdf pyinstaller

      - name: Build exe with PyInstaller
        run: |
          pyinstaller --noconsole --onefile --name "LsMaker" barcode_overlay_gui.py
          # Eğer repoda app.ico varsa ikonu eklemek için:
          # pyinstaller --noconsole --onefile --icon app.ico --name "A4 Barcode Composer" barcode_overlay_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/A4\ Barcode\ Composer.exe
